packages:
  - name: docker
    type: docker
    srcs:
      - "startup.sh"
      - "supervisor-ide-config.json"
      - "bin/*"
    argdeps:
      - imageRepoBase
      - gitpodDomain
    config:
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/ide/code:${version}
      buildArgs:
        OPENVSX_URL: https://open-vsx.${gitpodDomain}
